name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: version 
        run: go version 
    
      - name: Unit tests
        run: go test ./... -cover

  Style:
    name: Style
    runs-on: ubuntu-latest
    env:
      PATH: ${{ tools.go }}/go/1.20.0/x64/bin:$PATH

    steps:
      - name: Check formatting
        run: test -z $(go fmt ./...)
      
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Check Linting 
        run: staticcheck
