name: ci

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check out go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: Run tests
        run: go test ./... -cover

  formatting:
    name: Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check out go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: Run go fmt
        run: test -z $(go fmt ./...)

      - name: Install staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"

      - name: Run staticcheck
        run: staticcheck ./...

  security:
    name: Security
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check out go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: Install go sec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run go sec
        run: gosec ./...

  docker-build:
    name: Docker build and push
    runs-on: ubuntu-latest
    needs: [tests, formatting, security]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check out go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build notely binary
        run: ./scripts/buildprod.sh

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/notely:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/notely:latest
# //#
