me: ci

on:
    pull_request:
          branches: [main]
          jobs:
              tests:
                    name: tests
                          runs_on: ubuntu-latest

                                steps:
                                      - name: Set-up Go
                                              uses: actions/setup-go@v4
                                                      with:
                                                                go-version: "1.20"
                                                                        
                                                                      - name: Check out code
                                                                              uses: actions/checkout@v3

                                                                                    - name: Run tests
                                                                                            run: go test -cover ./...

                                                                                                style:
                                                                                                      name: format
                                                                                                            runs_on: ubuntu-latest

                                                                                                                  steps:
                                                                                                                        - name: Set-up Go
                                                                                                                                uses: actions/setup-go@v4
                                                                                                                                        with:
                                                                                                                                                  go-version: "1.20"
                                                                                                                                                          
                                                                                                                                                        - name: Check out code
                                                                                                                                                                uses: actions/checkout@v3

                                                                                                                                                                      - name: Run fmt
                                                                                                                                                                              run: go fmt ./...

