name: ci

on:
  pull_request:
    branches: [main]

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
    
      - name: check formatting
        run : test -z $(go fmt ./...)

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
        
      - name: check statically
        run: staticcheck ./...

  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
    
      - name: run tests 
        run: go test ./... -cover

      - name: Install gosec
        uses: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: run gosec
        run: gosec ./...

      - name: exit
        run: (exit 0)