name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run tests
        run: go test ./... -cover

      - name: install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run Security
        run: gosec ./...

  style:
    name: styles
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Format all directories
        run: test -z $(go fmt ./...)

      - name: install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Lint all directories
        run: staticcheck ./...
